#ifndef INIT_H
#define INIT_H
#include <stdlib.h>
#include <stddef.h>
#include "graphics.h"
#include "genlib.h"
#include "conio.h"
#include "extgraph.h"
#include "gcalloc.h"
#include "random.h"
#include "simpio.h"
#include "strlib.h"
#include <windows.h>
#include <olectl.h>
#include <stdio.h>
#include <mmsystem.h>
#include <wingdi.h>
#include <ole2.h>
#include <ocidl.h>
#include <winuser.h>
#include <time.h>
#include "imgui.h"
void Init();
void Display();
#endif
